export enum QuestionType {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  MULTIPLE_CHOICE_MULTI_SELECT = 'MULTIPLE_CHOICE_MULTI_SELECT',
  TRUE_FALSE = 'TRUE_FALSE',
  MATCHING = 'MATCHING',
  FILL_IN_THE_BLANK = 'FILL_IN_THE_BLANK',
  ORDERING = 'ORDERING',
}
